### ISSUE TITLE
submodules only partly installed

### ISSUE THREAD

**Issue by tortinator** [krr-up/latex-paper-template#2]
I created a new repo using the latex-paper-template, called asp-alternative-paradigm.
A .gitmodule file was created indicated the bibliography and the latex style to be included as submodules but no include folder was produced and thus neither submodule.
A submodule initialization did not change this.

**Comment by rkaminsk** [comment]
This seems to be a limitation (or bug) of github. I will modify the template to not include any submodules and rather add a rule in the Makefile to add the submodules initially.

**Comment by rkaminsk** [comment]
I added an init target to the Makefile, which adds and updates submodules once in the beginning.
